name: Build & Release Golang App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Build binaries
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o playground_windows_amd64.exe .
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o playground_linux_amd64 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o playground_linux_arm64 .
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o playground_darwin_arm64 .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            playground_windows_amd64.exe
            playground_linux_amd64
            playground_linux_arm64
            playground_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
